name: CI-CD

on:
  push:
    branches:
      - main 
jobs:
  build:
    runs-on: ubuntu-latest
    environment: CI/CD
    permissions:
      contents: read
      packages: write
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: setup docker
      uses: docker/setup-buildx-action@v2

    - name: login contianer registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      
    - name : create .env
      run: |
        echo "ROOT_PWD=${{ secrets.ROOT_PWD }}" >> .env
        echo "UPLOAD_PATH=${{ vars.UPLOAD_PATH }}" >> .env
        echo "REDIS_HOST=${{ secrets.REDIS_HOST }}" >> .env
        echo "REDIS_PORT=${{ secrets.REDIS_PORT }}" >> .env
        echo "REDIS_PWD=${{ secrets.REDIS_PWD }}" >> .env
  
    - name: docker create
      run : docker buildx create --use

    - name: docker build & push
      run: docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/${{ github.repository }}/storage:latest --push .
      
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: install ssh
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass

    - name: deploy
      env:
        ORACLE_IP: ${{ secrets.ORACLE_INSTANCE_IP }}
        SSH_PRIVATE_KEY: ${{ secrets.ORACLE_SSH_PRIVATE_KEY }}
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key
        chmod 600 private_key
        echo "ORACLE_IP: $ORACLE_IP"
        echo "SSH_PRIVATE_KEY: $SSH_PRIVATE_KEY"
        ssh -o StrictHostKeyChecking=no -i private_key ubuntu@$ORACLE_IP << 'EOF'
          docker login ghcr.io -u $GITHUB_ACTOR -p $GITHUB_TOKEN
          docker pull ghcr.io/${{ github.repository }}/storage:latest
          docker stop storage || true
          docker rm storage || true
          docker run -d -p 3002:3002 -v $(pwd)/storage:/app/storage  --network my-network --name storage ghcr.io/${{ github.repository }}/storage:latest
        EOF